export const ProductCategory = {
  CUIDADO_PERSONAL_HIGIENE: "CUIDADO_PERSONAL_HIGIENE",
  VITAMINAS_SUPLEMENTOS_NUTRICIONALES: "VITAMINAS_SUPLEMENTOS_NUTRICIONALES",
  RESPIRATORIOS_EXPECTORANTES: "RESPIRATORIOS_EXPECTORANTES",
  ANTIBIOTICOS_ANTIVIRALES: "ANTIBIOTICOS_ANTIVIRALES",
  DERMATOLOGICOS_TRATAMIENTOS_CUTANEOS: "DERMATOLOGICOS_TRATAMIENTOS_CUTANEOS",
  ANALGESICOS_ANTINFLAMATORIOS: "ANALGESICOS_ANTINFLAMATORIOS",
  MATERIAL_MEDICO_EQUIPOS: "MATERIAL_MEDICO_EQUIPOS",
  MEDICINA_NATURAL_HIDRATACION: "MEDICINA_NATURAL_HIDRATACION",
  PEDIATRICOS_LACTANCIA: "PEDIATRICOS_LACTANCIA",
  GASTROINTESTINALES_DIGESTIVOS: "GASTROINTESTINALES_DIGESTIVOS",
  GINECOLOGICOS_UROLOGICOS: "GINECOLOGICOS_UROLOGICOS",
  CARDIOVASCULARES_ANTIDIABETICOS: "CARDIOVASCULARES_ANTIDIABETICOS",
  OFTALMOLOGICOS: "OFTALMOLOGICOS",
  ANTIHISTAMINICOS_ANTIALERGICOS: "ANTIHISTAMINICOS_ANTIALERGICOS",
  NEUROLOGICOS_PSIQUIATRICOS: "NEUROLOGICOS_PSIQUIATRICOS",
  OTROS: "OTROS"
} as const

export type ProductCategory = typeof ProductCategory[keyof typeof ProductCategory]
